# Generated by Django 4.2.30 on 2026-09-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_announcement_banner_faq_genre_systemsetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration_ms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
