# Generated by Django 4.2.30 on 2026-09-01 12:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_song_duration_ms_alter_song_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(storage=api.models.AudioMediaStorage(), upload_to='songs/'),
        ),
    ]
